env:
  - GO111MODULE=on
  - CGO_ENABLED=1

builds:
  - id: hetty-darwin-amd64
    main: ./cmd/hetty
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly

  - id: hetty-linux-amd64
    main: ./cmd/hetty
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -mod=readonly

  - id: hetty-windows-amd64
    main: ./cmd/hetty
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
    ldflags:
      - -buildmode=exe

archives:
  -
    replacements:
        darwin: macOS
        linux: Linux
        windows: Windows
        386: i386
        amd64: x86_64
    format_overrides:
        - goos: windows
          format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
